name: recipe_application
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
 uses-material-design: true
 
 assets:
  - assets/images/item (1).png
  - assets/images/item (2).png
  - assets/images/item (3).png
  - assets/images/item (4).png
  - assets/images/item (5).png
  - assets/images/item (6).png
  - assets/images/item (7).png
  - assets/images/item (8).png
  - assets/images/item (9).png
  - assets/images/item (10).png
  - assets/images/item (11).png
  - assets/images/item (12).png
  - assets/images/item (13).png
  - assets/images/item (14).png
  - assets/images/item (15).png
  - assets/images/item (16).png
  - assets/images/item (17).png
  - assets/images/item (18).png
  - assets/images/item (19).png
  - assets/images/item (20).png
  - assets/images/item (21).png
  - assets/images/item (22).png
  - assets/images/item (23).png
  - assets/images/item (24).png
  - assets/images/item (25).png
  - assets/images/item (26).png
  - assets/images/item (27).png
  - assets/images/item (28).png
  - assets/images/item (29).png
  - assets/images/item (30).png
  - assets/images/item (31).png
  - assets/images/item (32).png
  - assets/images/item (33).png
  - assets/images/item (34).png
  - assets/images/item (35).png
  - assets/images/item (36).png
  - assets/images/item (37).png
  - assets/images/item (38).png
  - assets/images/item (39).png
  - assets/images/item (40).png
  - assets/images/item (41).png
  - assets/images/item (42).png
  - assets/images/item (43).png
  - assets/images/item (44).png
  - assets/images/item (45).png
  - assets/images/item (46).png
  - assets/images/item (47).png
  - assets/images/item (48).png
  - assets/images/item (49).png
  - assets/images/item (50).png
  - assets/images/item (51).png
  - assets/images/item (52).png
  - assets/images/item (53).png
  - assets/images/item (54).png
  - assets/images/item (55).png
  - assets/images/item (56).png
  - assets/images/item (57).png
  - assets/images/item (58).png
  - assets/images/item (59).png
  - assets/images/item (60).png
  - assets/images/item (61).png
  - assets/images/item (62).png
  - assets/images/item (63).png
  - assets/images/item (64).png
  - assets/images/item (65).png
  - assets/images/item (66).png
  - assets/images/item (67).png
  - assets/images/item (68).png
  - assets/images/item (69).png
  - assets/images/item (70).png
  - assets/images/item (71).png
  - assets/images/item (72).png
  - assets/images/item (73).png
  - assets/images/item (74).png
  - assets/images/item (75).png
  - assets/images/item (76).png
  - assets/images/item (77).png
  - assets/images/item (78).png
  - assets/images/item (79).png
  - assets/images/item (80).png
  - assets/images/item (81).png
  - assets/images/item (82).png
  - assets/images/item (83).png
  - assets/images/item (84).png
  - assets/images/item (85).png
  - assets/images/item (86).png
  - assets/images/item (87).png
  - assets/images/item (88).png
  - assets/images/item (89).png
  - assets/images/item (90).png
  - assets/images/item (91).png
  - assets/images/item (92).png
  - assets/images/item (93).png
  - assets/images/item (94).png
  - assets/images/item (95).png
  - assets/images/item (96).png
  - assets/images/item (97).png
  - assets/images/item (98).png
  - assets/images/item (99).png
  - assets/images/item (100).png
  - assets/images/item (101).png
  - assets/images/item (102).png
  - assets/images/item (103).png
  - assets/images/item (104).png
  - assets/images/item (105).png
  - assets/images/jump.gif
  - assets/images/log.gif
  - assets/images/jump copy.gif
  - assets/images/log copy.gif
  - assets/images/jump copy 2.gif
  - assets/images/log copy 2.gif
  - assets/images/jump copy 3.gif
  - assets/images/log copy 3.gif
  - assets/images/kerby.gif
  - assets/images/vegetable.png
  - assets/images/cooking.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An item asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 fonts:
    - family: Maplestory
      fonts:
        - asset: assets/fonts/Maplestory_Bold.ttf
          weight: 100
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages